# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod.dockerfile
tasks:
  - init: |
      sudo /etc/init.d/postgresql start  
      cd server
      mix deps.get
      mix ecto.migrate
    command: mix phx.server
# List the ports to expose. Learn more https://www.gitpod.io/docs/sudo /etc/init.d/postgresqlconfig-ports/
ports:
  - port: 3000
    onOpen: open-preview
  - port: 3030-6000
    onOpen: ignore